### ISSUE TITLE
quad-demo shows rectangle in place where the tetrahedron should be.

### ISSUE THREAD

**Issue by blondquirk** [kallaballa/GCV#1]
./src/quad/quad-demo 
OpenGL Version: 4.6 (Compatibility Profile) Mesa 22.0.5
OpenCL Platforms: 
	* OpenCL 3.0  = Intel(R) OpenCL HD Graphics
		  GL sharing: true
		  VAAPI media sharing: true

double free or corruption (!prev)
Segmentation fault
![tetra demo](https://user-images.githubusercontent.com/18315291/215632886-c421552c-6c1b-44d8-ab52-7d2b5746aa62.png)

**Comment by kallaballa** [comment]
quad demo is fine. the documentation is outdated and tetra demo missing. i reintroduced tetra (70aabaff141705dcf5c071e309b64fbbd7cfc31c) and will update the documentation.

**Comment by kallaballa** [comment]
renamed quad-demo to shader-demo: b8f7922001d3a285b13e93dae02b2d8254c2fc2c

**Comment by kallaballa** [comment]
Updated https://github.com/kallaballa/GCV/blob/main/README.md to include both shader-demo and tetra-demo.
