### ISSUE TITLE
optflow, face, pedestrian build fail

### ISSUE THREAD

**Issue by blondquirk** [kallaballa/GCV#2]
OpenCV has no header 'optflow.hpp' and 'face.hpp'.
pedestrian build fails due to undefined references to cv::HOGDescriptor set of functions.

OpenCV was built with the options recommended by GCV docs.

**Comment by kallaballa** [comment]
You are right i forgot to at the instructions for the opencv-contrib repo. will do!

**Comment by kallaballa** [comment]
I updated the README
